- Why do we not have a "barcode" type metadata category for viewing the rarefaction curve?
- I found a paper cited by the paper that we chose that actually did a similar analysis for the one that we were hoping to do 
  - called The role of the vaginal microbiome in distinguishing female chronic pelvic pain caused by endometriosis/adenomyosis
  - it used piecrust to look at the functional features of the vaginal microbiome of endometrial associated CPP vs regular CPP
  - what should we do? 
  - any tips for developing a biological rationale without simply copying other papers?
